CREATE TABLE MORTIFAGOS(
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    NOMBRE VARCHAR2(120) NOT NULL,
    ESTADO  VARCHAR2(20)NOT NULL,
    SANGRE VARCHAR2(20)NOT NULL,
    ESPECIALIDAD VARCHAR2(200) NOT NULL,
    ANTECEDENTES VARCHAR2(120) NOT NULL,
    IMAGEN VARCHAR2(100) NOT NULL,
 CONSTRAINT PK_MORTIFAGOS PRIMARY KEY (ID),
 CONSTRAINT CK_MORTIFAGOS_ESTADO CHECK (LOWER(ESTADO) IN ('vivo', 'muerto', 'desconocido')),
 CONSTRAINT CK_PMORTIFAGOS_SANGRE CHECK (LOWER(SANGRE) IN ('pura','mestiza','muggle','desconocido'))
);

INSERT INTO MORTIFAGOS (NOMBRE, ESTADO, SANGRE, ESPECIALIDAD, ANTECEDENTES, IMAGEN) 
VALUES ('Bellatrix Lestrange', 'vivo', 'pura', 
        'Magia oscura, tortura con Cruciatus', 
        'Condenada en Azkaban por torturar a los Longbottom', 
        'bellatrix.jpg');

INSERT INTO MORTIFAGOS (NOMBRE, ESTADO, SANGRE, ESPECIALIDAD, ANTECEDENTES, IMAGEN) 
VALUES ('Draco Malfoy', 'vivo', 'pura', 
        'Magia oscura básica, maldición Imperius', 
        'Participación forzada en complots de Voldemort', 
        'img/draco.jpg');

INSERT INTO MORTIFAGOS (NOMBRE, ESTADO, SANGRE, ESPECIALIDAD, ANTECEDENTES, IMAGEN) 
VALUES ('Lucius Malfoy', 'vivo', 'pura', 
        'Influencia política, artefactos tenebrosos', 
        'Mortífago declarado, sobornos y chantajes', 
        'img/lucius.jpg');

INSERT INTO MORTIFAGOS (NOMBRE, ESTADO, SANGRE, ESPECIALIDAD, ANTECEDENTES, IMAGEN) 
VALUES ('Antonin Dolohov', 'vivo', 'pura', 
        'Duelos, maldiciones letales', 
        'Condenado por asesinato y tortura de magos y muggles', 
        'img/dolohov.jpg');

INSERT INTO MORTIFAGOS (NOMBRE, ESTADO, SANGRE, ESPECIALIDAD, ANTECEDENTES, IMAGEN) 
VALUES ('Fenrir Greyback', 'vivo', 'desconocido', 
        'Licántropo, ataques cuerpo a cuerpo', 
        'Ataques a niños y muggles, colaborador de Voldemort', 
        'img/fenrir_greyback.jpg');

INSERT INTO MORTIFAGOS (NOMBRE, ESTADO, SANGRE, ESPECIALIDAD, ANTECEDENTES, IMAGEN) 
VALUES ('Barty Crouch Jr.', 'muerto', 'desconocido', 
        'Maldiciones imperdonables, suplantación con multijugos', 
        'Evasión de Azkaban, secuestro de Ojo-Loco Moody', 
        'img/barty_jr.jpg');

INSERT INTO MORTIFAGOS (NOMBRE, ESTADO, SANGRE, ESPECIALIDAD, ANTECEDENTES, IMAGEN) 
VALUES ('Severus Snape', 'muerto', 'mestiza', 
        'Pociones, oclumancia y legeremancia', 
        'Doble agente entre la Orden del Fénix y Voldemort', 
        'img/snape.jpg');


