DROP TABLE MORTIFAGOS;

CREATE TABLE MORTIFAGOS(
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    NOMBRE VARCHAR2(120) NOT NULL,
    ESTADO  VARCHAR2(20)NOT NULL,
    SANGRE VARCHAR2(20)NOT NULL,
    ESPECIALIDAD VARCHAR2(200) NOT NULL,
    ANTECEDENTES VARCHAR2(120) NOT NULL,
    IMAGEN VARCHAR2(100) NOT NULL,
 CONSTRAINT PK_MORTIFAGOS PRIMARY KEY (ID),
 CONSTRAINT CK_MORTIFAGOS_ESTADO CHECK (LOWER(ESTADO) IN ('vivo', 'muerto', 'desconocido')),
 CONSTRAINT CK_PMORTIFAGOS_SANGRE CHECK (LOWER(SANGRE) IN ('pura','mestiza','muggle','desconocido'))
);

INSERT INTO MORTIFAGOS (NOMBRE, ESTADO, SANGRE, ESPECIALIDAD, ANTECEDENTES, IMAGEN) 
VALUES ('Bellatrix Lestrange', 'vivo', 'Pura', 
        'Magia oscura, tortura con Cruciatus', 
        'Condenada en Azkaban por torturar a los Longbottom', 
        'img/bellatrix.jpg');

INSERT INTO MORTIFAGOS (NOMBRE, ESTADO, SANGRE, ESPECIALIDAD, ANTECEDENTES, IMAGEN) 
VALUES ('Draco Malfoy', 'vivo', 'Pura', 
        'Magia oscura básica, maldición Imperius', 
        'Participación forzada en complots de Voldemort', 
        'img/draco.jpg');

INSERT INTO MORTIFAGOS (NOMBRE, ESTADO, SANGRE, ESPECIALIDAD, ANTECEDENTES, IMAGEN) 
VALUES ('Lucius Malfoy', 'vivo', 'Pura', 
        'Influencia política, artefactos tenebrosos', 
        'Mortífago declarado, sobornos y chantajes', 
        'img/lucius.jpg');

INSERT INTO MORTIFAGOS (NOMBRE, ESTADO, SANGRE, ESPECIALIDAD, ANTECEDENTES, IMAGEN) 
VALUES ('Antonin Dolohov', 'vivo', 'Pura', 
        'Duelos, maldiciones letales', 
        'Condenado por asesinato y tortura de magos y muggles', 
        'img/dolohov.jpg');

INSERT INTO MORTIFAGOS (NOMBRE, ESTADO, SANGRE, ESPECIALIDAD, ANTECEDENTES, IMAGEN) 
VALUES ('Fenrir Greyback', 'vivo', 'Desconocido', 
        'Licántropo, ataques cuerpo a cuerpo', 
        'Ataques a niños y muggles, colaborador de Voldemort', 
        'img/fenrir_greyback.jpg');

INSERT INTO MORTIFAGOS (NOMBRE, ESTADO, SANGRE, ESPECIALIDAD, ANTECEDENTES, IMAGEN) 
VALUES ('Barty Crouch Jr.', 'muerto', 'Desconocido', 
        'Maldiciones imperdonables, suplantación con multijugos', 
        'Evasión de Azkaban, secuestro de Ojo-Loco Moody', 
        'img/barty_jr.jpg');

INSERT INTO MORTIFAGOS (NOMBRE, ESTADO, SANGRE, ESPECIALIDAD, ANTECEDENTES, IMAGEN) 
VALUES ('Severus Snape', 'muerto', 'Mestiza', 
        'Pociones, oclumancia y legeremancia', 
        'Doble agente entre la Orden del Fénix y Voldemort', 
        'img/snape.jpg');
INSERT INTO MORTIFAGOS (NOMBRE, ESTADO, SANGRE, ESPECIALIDAD, ANTECEDENTES, IMAGEN) 
VALUES ('Igor Karkarov', 'muerto', 'Desconocido',
        'Artes Oscuras y dirección estratégica',
        'Ex director de Durmstrang, delató mortífagos tras su captura',
        'img/karkarov.jpg');

INSERT INTO MORTIFAGOS (NOMBRE, ESTADO, SANGRE, ESPECIALIDAD, ANTECEDENTES, IMAGEN) 
VALUES ('Corban Yaxley', 'desconocido', 'Pura',
        'Manipulación política y persecución de muggles',
        'Participó en la toma del Ministerio',
        'img/yaxley.jpg');

INSERT INTO MORTIFAGOS (NOMBRE, ESTADO, SANGRE, ESPECIALIDAD, ANTECEDENTES, IMAGEN) 
VALUES ('Selwyn', 'desconocido', 'Pura',
        'Apoyo táctico y duelos',
        'Participó en la captura de Harry Potter',
        'img/selwyn.jpg');

INSERT INTO MORTIFAGOS (NOMBRE, ESTADO, SANGRE, ESPECIALIDAD, ANTECEDENTES, IMAGEN) 
VALUES ('Gibbon', 'muerto', 'Desconocido',
        'Ataques encubiertos',
        'Murió por fuego amigo durante una incursión',
        'img/gibbon.jpg');

INSERT INTO MORTIFAGOS (NOMBRE, ESTADO, SANGRE, ESPECIALIDAD, ANTECEDENTES, IMAGEN) 
VALUES ('Avery (Sr.)', 'desconocido', 'Pura',
        'Maldiciones imperdonables',
        'Mortífago activo en la Primera Guerra',
        'img/avery_sr.jpg');



INSERT INTO MORTIFAGOS (NOMBRE, ESTADO, SANGRE, ESPECIALIDAD, ANTECEDENTES, IMAGEN) 
VALUES ('Crabbe Sr.', 'desconocido', 'Pura',
        'Influencia y apoyo logístico',
        'Padre de Vincent Crabbe y mortífago declarado',
        'img/crabbe_sr.jpg');

INSERT INTO MORTIFAGOS (NOMBRE, ESTADO, SANGRE, ESPECIALIDAD, ANTECEDENTES, IMAGEN) 
VALUES ('Goyle Sr.', 'desconocido', 'Pura',
        'Apoyo en misiones de intimidación',
        'Padre de Gregory Goyle, seguidor fiel',
        'img/goyle_sr.jpg');


COMMIT;

